---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: haproxy
  namespace: haproxy
  labels:
    app: haproxy
spec:
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: docker.io/haproxy:2.9.6-alpine
        resources:
          requests:
            cpu: 20m
            memory: 64Mi
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 3
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          tcpSocket:
            port: 5432
        ports:
        - containerPort: 5432
          protocol: TCP
          name: psq16sitepulse
        - containerPort: 7000
          protocol: TCP
          name: haproxy-stats
        volumeMounts:
        - mountPath: /usr/local/etc/haproxy
          name: config
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        configMap:
          name: haproxy
