---
apiVersion: v1
kind: Service
metadata:
  name: haproxy
  namespace: haproxy
spec:
  selector:
    app: haproxy
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: psq16sitepulse
