---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: site-pulse-360-backend
  name: site-pulse-360-backend
  namespace: site-pulse-360
spec:
  selector:
    matchLabels:
      app: site-pulse-360-backend
  template:
    metadata:
      labels:
        app: site-pulse-360-backend
    spec:
      imagePullSecrets:
      - name: registry-gitlab-diller
      automountServiceAccountToken: true
      serviceAccount: site-pulse-backend-leader-election
      containers:
      - image: ${CI_REGISTRY_IMAGE}/backend:${VERSION_BACKEND}
        name: backend
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
        env:
        - name: DB_HOST
          value: "${DB_HOST}"
        - name: DB_PORT
          value: "${DB_PORT}"
        - name: DB_USER
          value: "${DB_USER}"
        - name: DB_PASSWORD
          value: "${DB_PASSWORD}"
        - name: DB_NAME
          value: "${DB_NAME}"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /api
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        ports:
        - containerPort: 3000
          name: http
