---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: site-pulse-backend-leader-election
  namespace: site-pulse-360
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: site-pulse-backend-leader-election
subjects:
- kind: ServiceAccount
  name: site-pulse-backend-leader-election
