---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: site-pulse-backend-leader-election
  namespace: site-pulse-360
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
