---
apiVersion: v1
kind: Service
metadata:
  name: site-pulse-360-frontend
  namespace: site-pulse-360
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: site-pulse-360-frontend
